export const WORKSTREAM_STATUSES = [
  "ADMITTED_EVALUATION",
  "WATCH",
  "HOLD",
  "BLOCKED_EXTERNAL",
  "NOT_ADOPTED",
  "UNAVAILABLE",
] as const;
export type WorkstreamStatus = (typeof WORKSTREAM_STATUSES)[number];

export const FAMILIES = [
  "runtime",
  "model",
  "quantization",
  "memory",
  "eval",
  "data",
  "serving",
  "research",
  "vertical",
] as const;
export type Family = (typeof FAMILIES)[number];

export interface Workstream {
  id: string;
  code: string;
  title: string;
  family: Family;
  owner: string;
  hypothesis: string;
  baseline: string;
  status: WorkstreamStatus;
  productionDisposition: "HOLD";
  productionAuthorized: false;
  evidence: string;
  blocker: string | null;
  issue: string | null;
  selectedForRelease: boolean;
}

export const WORKSTREAMS: Workstream[] = [
  {
    id: "F01",
    code: "F01",
    title: "Edge0 exact-route expert prefetch",
    family: "runtime",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Exact-route-preserving expert prefetch reduces I/O without changing route identity.",
    baseline: "python/szl_frontier/edge_lane.py SOFTWARE gates; no live Edge0 device in this tree.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Existing edge_lane + edge_witness owners. Measure actual I/O and memory before adoption.",
    blocker: "Hardware-specific qualification not executed in this seat.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F02",
    code: "F02",
    title: "Spark-X2.5 context-budget ladder",
    family: "runtime",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "A declared context budget can distinguish attention masks from cache eviction.",
    baseline: "Kimi HY4 Spark intake wave; qualification not inherited.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "frontier/waves/2026-09-08-kimi-hy4-spark.json",
    blocker: "Attention-mask vs eviction tests not executed here.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F03",
    code: "F03",
    title: "Bonsai packing + runtime",
    family: "model",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Model, packing, transforms, and runtime must qualify together.",
    baseline: "Draft PR #187 Ternary Bonsai 2 27B exact-source watch under HOLD.",
    status: "HOLD",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-frontier/pull/187",
    blocker: "Draft / HOLD. Do not merge without required checks and review.",
    issue: "187",
    selectedForRelease: false,
  },
  {
    id: "F04",
    code: "F04",
    title: "DeepSeek / DSpark serving boundary",
    family: "serving",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Aliases, cache/state, and speculative paths must be exact-source bound.",
    baseline: "Issue #134 DeepSeek-V4.1-Flash CED + compressed-KV. Successors do not inherit qualification.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-frontier/issues/134",
    blocker: "Executable qualification stays with Forge / Serve / GPU Bridge.",
    issue: "134",
    selectedForRelease: false,
  },
  {
    id: "F05",
    code: "F05",
    title: "Tencent SAS approximate attention",
    family: "runtime",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Approximate attention needs matched quality/resource tests, not a catalog flag.",
    baseline: "Not independently qualified in this organ.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead only.",
    blocker: "Primary source, license, and hardware compatibility not closed.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F06",
    code: "F06",
    title: "Granite / Lyte forecast uncertainty",
    family: "eval",
    owner: "szl-holdings/a11oy",
    hypothesis: "Forecast uncertainty with rolling holdouts and statistical baselines.",
    baseline: "Granite PatchTST FM r2 wave; Lyte product journey lives in a11oy, not a second flagship.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "frontier/waves/2026-09-12-granite-patchtst-fm-r2.json",
    blocker: "Product journey not this organ. Rolling holdouts not executed here.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F07",
    code: "F07",
    title: "Per-tensor GGUF canaries",
    family: "quantization",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Numerical canaries plus SZL task regressions before any GGUF serve.",
    baseline: "MiniCPM5 GGUF wave + matched worker. Compact baselines preserved.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "frontier/waves/2026-09-08-minicpm5-gguf.json",
    blocker: "Forge evaluation owner. No random-weight substitute.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F08",
    code: "F08",
    title: "AutoRound export provenance",
    family: "quantization",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Quantizer scheme must match export; calibration provenance retained.",
    baseline: "Not adopted until scheme/export identity is bound.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead.",
    blocker: "No AutoRound qualification receipt in this tree.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F09",
    code: "F09",
    title: "Kernel Hub typed revisions",
    family: "runtime",
    owner: "szl-holdings/szl-kernels",
    hypothesis: "Typed repositories, immutable revisions, build/runtime compatibility.",
    baseline: "Issue #155 Hugging Face Kernels v0.17.0 trust/capability boundary.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-frontier/issues/155",
    blocker: "Do not relabel executable kernels as trained models.",
    issue: "155",
    selectedForRelease: false,
  },
  {
    id: "F10",
    code: "F10",
    title: "Compact baselines",
    family: "model",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Preserve MINI / ReceiptAgent / MiniCPM / Qwen comparators.",
    baseline: "Forge PR #345 MiniCPM baseline preserve (draft/HOLD).",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-forge/pull/345",
    blocker: "Comparators are evidence, not production models.",
    issue: null,
    selectedForRelease: true,
  },
  {
    id: "F11",
    code: "F11",
    title: "Nex observation/action harness",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Observation, action, independent verification, and recovery stay distinct.",
    baseline: "Adversary campaign in this organ is software-only.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "src/lib/adversary/campaign.ts",
    blocker: "No Nex physical/operational coupling.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F12",
    code: "F12",
    title: "UltraData rights + holdouts",
    family: "data",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Rights review, failure traces, labels, loss masks, held-out separation.",
    baseline: "Not admitted. A researched not-adopted decision is valid.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead.",
    blocker: "Rights review not closed.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F13",
    code: "F13",
    title: "Open-SWE-Traces patch custody",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Repository/task holdouts, patch custody, replay, anti-test-tampering.",
    baseline: "Not adopted pending licensed task family.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead.",
    blocker: "No owned task suite in this organ.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F14",
    code: "F14",
    title: "ScienceIDE executable tasks",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Repository-derived executable environments with acceptance tests.",
    baseline: "Atria Dawn Preview issue #166 blocked-external.",
    status: "BLOCKED_EXTERNAL",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-frontier/issues/166",
    blocker: "External model candidate; not this organ's runtime.",
    issue: "166",
    selectedForRelease: false,
  },
  {
    id: "F15",
    code: "F15",
    title: "ModularRSI isolated harness",
    family: "research",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Isolated harness-component evolution on licensed tasks.",
    baseline: "Not adopted.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead.",
    blocker: "Licensed task family not selected.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F16",
    code: "F16",
    title: "SoL-Pi evidence-preserving compaction",
    family: "memory",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Reduce token traffic without losing source spans, failures, or trust boundaries.",
    baseline: "Memory Covenant already seals provenance. Compaction is R2 research.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "src/lib/covenant — deny-by-default memory plane.",
    blocker: "Adversarial delayed-recall tests not executed as a separate suite.",
    issue: null,
    selectedForRelease: true,
  },
  {
    id: "F17",
    code: "F17",
    title: "Reef bounded learning candidates",
    family: "research",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Bounded learning candidates; immutable reviewed promotion only.",
    baseline: "Training remains deferred. Default paid budget $0.",
    status: "HOLD",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Training readiness ≠ trained-model qualification.",
    blocker: "No exact source/data/hardware/budget plan approved.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F18",
    code: "F18",
    title: "ALTK consistency metrics",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Mean@k, all-runs Pass^k, and any-run Pass@k stay distinct.",
    baseline: "python/payload consistency() — null is unobserved, not failure.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "python/payload/szl_payload_contract.py consistency()",
    blocker: "No live task matrix in this seat.",
    issue: null,
    selectedForRelease: true,
  },
  {
    id: "F19",
    code: "F19",
    title: "Emergence World contamination tests",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Delayed-memory and cross-agent contamination must be tested.",
    baseline: "Covenant isolation + adversary campaign. Not a world-model runtime.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "src/lib/covenant isolation gates.",
    blocker: "No Emergence World environment admitted.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F20",
    code: "F20",
    title: "OUI schema-bound interface proposals",
    family: "research",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Generated views cannot grant data or execution authority.",
    baseline: "This operator plane: server-owned truth, disabled promotion.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Frontier operator UI in this repository.",
    blocker: "Generated layout remains a proposal until schema + permissions agree.",
    issue: null,
    selectedForRelease: true,
  },
  {
    id: "F21",
    code: "F21",
    title: "TRL / Transformers / Accelerate / PEFT",
    family: "runtime",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Isolated version/recipe qualification. Moving main inherits nothing.",
    baseline: "Multiple exact-source waves (PEFT 0.20, TRL AsyncGRPO, activation offload).",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "frontier/waves 2026-09-10 through 2026-09-17 TRL/PEFT successors.",
    blocker: "Forge evaluation. No dependency bump from this console.",
    issue: "142",
    selectedForRelease: false,
  },
  {
    id: "F22",
    code: "F22",
    title: "ShadowPEFT attach/detach",
    family: "runtime",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Attached/detached quality, memory, export, and reload must be measured.",
    baseline: "PEFT fallback trainability successor #177.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-frontier/issues/177",
    blocker: "Known-bad controls not executed in this seat.",
    issue: "177",
    selectedForRelease: false,
  },
  {
    id: "F23",
    code: "F23",
    title: "vLLM / SGLang / Omni / TEI",
    family: "serving",
    owner: "szl-holdings/szl-serve",
    hypothesis: "Exact backend and hardware qualification, not catalog flags.",
    baseline: "vLLM 0.29, Omni rc1, SGLang DeepSeek kernels, TEI v1.9.4 issues open.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Issues #129, #157, #162, #168.",
    blocker: "Serve/GPU-bridge owners. Configured endpoints are not qualified workers.",
    issue: "168",
    selectedForRelease: false,
  },
  {
    id: "F24",
    code: "F24",
    title: "Agnes hybrid-memory isolation",
    family: "memory",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "State isolation and hybrid-memory/attention ablations.",
    baseline: "Memory Covenant tenant isolation is software-tested.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Covenant engine isolation gates.",
    blocker: "Agnes architecture not admitted as a runtime.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F25",
    code: "F25",
    title: "YARQA / RLT looped computation",
    family: "research",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Distinct architectures, causal tests, bounded iteration.",
    baseline: "Ouroboros cycle MAX_ROUNDS=2 always terminates.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "python/szl_frontier/ouroboros.py",
    blocker: "YARQA/RLT not installed. Cycle is proposal-only.",
    issue: null,
    selectedForRelease: true,
  },
  {
    id: "F26",
    code: "F26",
    title: "AuK consented speech",
    family: "model",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Consented speech generation/editing; speaker and content tests.",
    baseline: "Issue #136 Tencent AuK / AuK-Flash.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "https://github.com/szl-holdings/szl-frontier/issues/136",
    blocker: "Identity overclaim forbidden. No voice-clone objective.",
    issue: "136",
    selectedForRelease: false,
  },
  {
    id: "F27",
    code: "F27",
    title: "LACI localize/rollback",
    family: "runtime",
    owner: "szl-holdings/szl-serve",
    hypothesis: "Localize/rollback/regenerate only on supported backends.",
    baseline: "Not verified in this organ.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead.",
    blocker: "Supported-backend matrix missing.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F28",
    code: "F28",
    title: "VoiceTrace speaker-aware retrieval",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Consented speaker-aware retrieval without identity overclaiming.",
    baseline: "Open Yap 1K speech-data-sandbox HOLD in Python control plane.",
    status: "HOLD",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "python/szl_frontier catalog Open Yap 1K admission.",
    blocker: "Identity inference prohibited. Full corpus DUA held.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F29",
    code: "F29",
    title: "Zing simulated environments",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Simulated environments stay separated from physical or operational truth.",
    baseline: "Shadowbroker is a simulated read-only connector. No packets, no targeting.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "src/lib/intel/feed.ts — simulated connector.",
    blocker: "Never promote simulation to live vessel/effector feed.",
    issue: null,
    selectedForRelease: true,
  },
  {
    id: "F30",
    code: "F30",
    title: "Nemotron math verifier lane",
    family: "eval",
    owner: "szl-holdings/szl-forge",
    hypothesis: "Generation/verifier/refinement/selection; formal proof stays separate.",
    baseline: "Lean locked-8 lives in lutar-lean, not here.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Λ remains Conjecture 1.",
    blocker: "Do not transfer upstream benchmark numbers into marketing.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F31",
    code: "F31",
    title: "Retrieval / reranking",
    family: "eval",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Hybrid retrieval, access filtering, citation fidelity, fresh indexes.",
    baseline: "Yachay public 575 chunks. Private graph unpublished. ABSTAIN on miss.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Issue #182 Qdrant FineWeb-10B + Supernova; #170 FAISS metric.",
    blocker: "Index is DATA, never weights. LIVE retrieval is never fabricated.",
    issue: "170",
    selectedForRelease: true,
  },
  {
    id: "F32",
    code: "F32",
    title: "Existing tooling reconciliation",
    family: "research",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Reconcile already-admitted research and runtime-integrity waves.",
    baseline: "76 governed waves in frontier/waves. Do not duplicate publishers.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "frontier/waves/ (76 files) + python control plane.",
    blocker: "Issue #151 residual A11oy/HF inventory drift remains open.",
    issue: "151",
    selectedForRelease: true,
  },
  {
    id: "F33",
    code: "F33",
    title: "Optimum-Intel / OpenVINO",
    family: "runtime",
    owner: "szl-holdings/szl-gpu-bridge",
    hypothesis: "Verify devices/operators; export/reload and correctness before CPU/GPU/NPU.",
    baseline: "Not adopted. GPU-bridge is the owner.",
    status: "WATCH",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "Intake lead.",
    blocker: "No device/operator matrix in this tree.",
    issue: null,
    selectedForRelease: false,
  },
  {
    id: "F34",
    code: "F34",
    title: "Funes-style memory",
    family: "memory",
    owner: "szl-holdings/szl-frontier",
    hypothesis: "Authoritative passages, deterministic chunks, embedding identity, hybrid retrieval, rollback, secret scanning.",
    baseline: "Memory Covenant is the owner. Extend, do not replace.",
    status: "ADMITTED_EVALUATION",
    productionDisposition: "HOLD",
    productionAuthorized: false,
    evidence: "src/lib/covenant engine + Yachay fold.",
    blocker: "Private 9464-node graph unpublished. 0 admitted to gradients.",
    issue: null,
    selectedForRelease: true,
  },
];

export const RESEARCH_TARGETS = [
  {
    id: "R1",
    title: "Evidence-preserving adaptive compute",
    status: "HOLD" as const,
    note: "Select eligible model/runtime/context/precision within a declared budget. Not authorized here.",
  },
  {
    id: "R2",
    title: "Provenance-preserving context compaction",
    status: "HOLD" as const,
    note: "F16 lead. Test adversarial and delayed recall before adoption.",
  },
  {
    id: "R3",
    title: "Artifact/runtime compatibility verification",
    status: "HOLD" as const,
    note: "Unsupported combinations must stop. Missing models return unavailable.",
  },
  {
    id: "R4",
    title: "Contamination-contained memory",
    status: "ADMITTED_EVALUATION" as const,
    note: "Covenant origin/trust labels. Delayed-effect fixtures not yet a separate suite.",
  },
  {
    id: "R5",
    title: "Evidence-bound workspaces",
    status: "ADMITTED_EVALUATION" as const,
    note: "This console generates views. It cannot grant data or execution authority.",
  },
  {
    id: "R6",
    title: "Repository-derived vertical task environments",
    status: "WATCH" as const,
    note: "Owned task suites remain with product repos (a11oy, lyte, etc.).",
  },
  {
    id: "R7",
    title: "Reliable multimodal observations",
    status: "WATCH" as const,
    note: "Observed / inferred / predicted / simulated stay labeled. NeoMME smoke is SOFTWARE.",
  },
] as const;

export const VERTICAL_JOURNEYS = [
  {
    id: "lyte",
    title: "Lyte",
    owner: "szl-holdings/a11oy",
    path: "source metric → normalize → forecast/drift → evidence → human review",
    note: "Not this organ. Rolling time holdouts required.",
  },
  {
    id: "terra",
    title: "Terra / David Leads",
    owner: "szl-holdings/david-leads",
    path: "official-source observation → entity resolution → evidence → research workflow",
    note: "Contact-permission and underwriting restrictions preserved.",
  },
  {
    id: "maritime",
    title: "Maritime / Vessels",
    owner: "szl-holdings/a11oy",
    path: "authorized AIS → gap detection → voyage analysis → timestamped evidence",
    note: "Historical AIS is not a live vessel feed. Canonical product, not a new alias.",
  },
  {
    id: "prism",
    title: "PRISM / Counsel",
    owner: "szl-holdings/a11oy",
    path: "matter → retrieval → jurisdiction/version-aware reasoning → cited draft → review",
    note: "Generated legal interpretation is not authoritative.",
  },
  {
    id: "puriq",
    title: "Finance / PURIQ",
    owner: "szl-holdings/a11oy",
    path: "lineage → leakage-controlled analysis → paper evaluation → human review",
    note: "No automatic live-trading authorization.",
  },
  {
    id: "advisory",
    title: "Advisory",
    owner: "szl-holdings/a11oy",
    path: "consented client context → task coordination → evidence-backed recommendations",
    note: "Private client information stays out of public cards.",
  },
  {
    id: "forge",
    title: "Forge",
    owner: "szl-holdings/szl-forge",
    path: "admitted data → exact recipe → qualified worker → artifact → held-out eval → review",
    note: "Training deferred. Budget $0 unless separately approved.",
  },
] as const;

export function workstreamTone(
  status: WorkstreamStatus,
): "allow" | "pending" | "deny" | "accent" | "default" {
  switch (status) {
    case "ADMITTED_EVALUATION":
      return "accent";
    case "WATCH":
      return "pending";
    case "HOLD":
    case "BLOCKED_EXTERNAL":
      return "deny";
    case "NOT_ADOPTED":
      return "default";
    default:
      return "default";
  }
}

export function filterWorkstreams(
  items: Workstream[],
  opts: { q?: string; family?: string; status?: string; selected?: boolean },
): Workstream[] {
  const q = (opts.q ?? "").trim().toLowerCase();
  return items.filter((w) => {
    if (opts.family && opts.family !== "all" && w.family !== opts.family) return false;
    if (opts.status && opts.status !== "all" && w.status !== opts.status) return false;
    if (opts.selected && !w.selectedForRelease) return false;
    if (!q) return true;
    const hay = `${w.code} ${w.title} ${w.owner} ${w.hypothesis} ${w.evidence}`.toLowerCase();
    return hay.includes(q);
  });
}

export function workstreamSummary(items: Workstream[] = WORKSTREAMS) {
  const byStatus = Object.fromEntries(WORKSTREAM_STATUSES.map((s) => [s, 0])) as Record<
    WorkstreamStatus,
    number
  >;
  for (const w of items) byStatus[w.status] += 1;
  return {
    total: items.length,
    selectedForRelease: items.filter((w) => w.selectedForRelease).length,
    productionAuthorized: 0,
    byStatus,
  };
}
