/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AdversaryRouteImport } from './routes/adversary'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as FrontierRouteImport } from './routes/frontier'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as HarborRouteImport } from './routes/harbor'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ApiCycleRouteImport } from './routes/api/cycle'
import { Route as ApiEstateRouteImport } from './routes/api/estate'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiSourceRouteImport } from './routes/api/source'
import { Route as ApiWorkstreamsRouteImport } from './routes/api/workstreams'
import { Route as ApiAgentStateRouteImport } from './routes/api/agent-state'
import { Route as ApiCodexRouteImport } from './routes/api/codex'
import { Route as ApiKernelsRouteImport } from './routes/api/kernels'
import { Route as ApiLeasesRouteImport } from './routes/api/leases'
import { Route as ApiPinRouteImport } from './routes/api/pin'
import { Route as ApiTriadRouteImport } from './routes/api/triad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdversaryRoute = AdversaryRouteImport.update({
  id: '/adversary',
  path: '/adversary',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontierRoute = FrontierRouteImport.update({
  id: '/frontier',
  path: '/frontier',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const HarborRoute = HarborRouteImport.update({
  id: '/harbor',
  path: '/harbor',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCycleRoute = ApiCycleRouteImport.update({
  id: '/api/cycle',
  path: '/api/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstateRoute = ApiEstateRouteImport.update({
  id: '/api/estate',
  path: '/api/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkstreamsRoute = ApiWorkstreamsRouteImport.update({
  id: '/api/workstreams',
  path: '/api/workstreams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStateRoute = ApiAgentStateRouteImport.update({
  id: '/api/agent-state',
  path: '/api/agent-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexRoute = ApiCodexRouteImport.update({
  id: '/api/codex',
  path: '/api/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKernelsRoute = ApiKernelsRouteImport.update({
  id: '/api/kernels',
  path: '/api/kernels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeasesRoute = ApiLeasesRouteImport.update({
  id: '/api/leases',
  path: '/api/leases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPinRoute = ApiPinRouteImport.update({
  id: '/api/pin',
  path: '/api/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriadRoute = ApiTriadRouteImport.update({
  id: '/api/triad',
  path: '/api/triad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/adversary': typeof AdversaryRoute
  '/brain': typeof BrainRoute
  '/frontier': typeof FrontierRoute
  '/gates': typeof GatesRoute
  '/harbor': typeof HarborRoute
  '/ingest': typeof IngestRoute
  '/intel': typeof IntelRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/models': typeof ModelsRoute
  '/proof': typeof ProofRoute
  '/api/cycle': typeof ApiCycleRoute
  '/api/estate': typeof ApiEstateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/source': typeof ApiSourceRoute
  '/api/workstreams': typeof ApiWorkstreamsRoute
  '/api/agent-state': typeof ApiAgentStateRoute
  '/api/codex': typeof ApiCodexRoute
  '/api/kernels': typeof ApiKernelsRoute
  '/api/leases': typeof ApiLeasesRoute
  '/api/pin': typeof ApiPinRoute
  '/api/triad': typeof ApiTriadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/adversary': typeof AdversaryRoute
  '/brain': typeof BrainRoute
  '/frontier': typeof FrontierRoute
  '/gates': typeof GatesRoute
  '/harbor': typeof HarborRoute
  '/ingest': typeof IngestRoute
  '/intel': typeof IntelRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/models': typeof ModelsRoute
  '/proof': typeof ProofRoute
  '/api/cycle': typeof ApiCycleRoute
  '/api/estate': typeof ApiEstateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/source': typeof ApiSourceRoute
  '/api/workstreams': typeof ApiWorkstreamsRoute
  '/api/agent-state': typeof ApiAgentStateRoute
  '/api/codex': typeof ApiCodexRoute
  '/api/kernels': typeof ApiKernelsRoute
  '/api/leases': typeof ApiLeasesRoute
  '/api/pin': typeof ApiPinRoute
  '/api/triad': typeof ApiTriadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/adversary': typeof AdversaryRoute
  '/brain': typeof BrainRoute
  '/frontier': typeof FrontierRoute
  '/gates': typeof GatesRoute
  '/harbor': typeof HarborRoute
  '/ingest': typeof IngestRoute
  '/intel': typeof IntelRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/models': typeof ModelsRoute
  '/proof': typeof ProofRoute
  '/api/cycle': typeof ApiCycleRoute
  '/api/estate': typeof ApiEstateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/source': typeof ApiSourceRoute
  '/api/workstreams': typeof ApiWorkstreamsRoute
  '/api/agent-state': typeof ApiAgentStateRoute
  '/api/codex': typeof ApiCodexRoute
  '/api/kernels': typeof ApiKernelsRoute
  '/api/leases': typeof ApiLeasesRoute
  '/api/pin': typeof ApiPinRoute
  '/api/triad': typeof ApiTriadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/adversary'
    | '/brain'
    | '/frontier'
    | '/gates'
    | '/harbor'
    | '/ingest'
    | '/intel'
    | '/memory'
    | '/mesh'
    | '/models'
    | '/proof'
    | '/api/cycle'
    | '/api/estate'
    | '/api/health'
    | '/api/ready'
    | '/api/source'
    | '/api/workstreams'
    | '/api/agent-state'
    | '/api/codex'
    | '/api/kernels'
    | '/api/leases'
    | '/api/pin'
    | '/api/triad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/adversary'
    | '/brain'
    | '/frontier'
    | '/gates'
    | '/harbor'
    | '/ingest'
    | '/intel'
    | '/memory'
    | '/mesh'
    | '/models'
    | '/proof'
    | '/api/cycle'
    | '/api/estate'
    | '/api/health'
    | '/api/ready'
    | '/api/source'
    | '/api/workstreams'
    | '/api/agent-state'
    | '/api/codex'
    | '/api/kernels'
    | '/api/leases'
    | '/api/pin'
    | '/api/triad'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/adversary'
    | '/brain'
    | '/frontier'
    | '/gates'
    | '/harbor'
    | '/ingest'
    | '/intel'
    | '/memory'
    | '/mesh'
    | '/models'
    | '/proof'
    | '/api/cycle'
    | '/api/estate'
    | '/api/health'
    | '/api/ready'
    | '/api/source'
    | '/api/workstreams'
    | '/api/agent-state'
    | '/api/codex'
    | '/api/kernels'
    | '/api/leases'
    | '/api/pin'
    | '/api/triad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AdversaryRoute: typeof AdversaryRoute
  BrainRoute: typeof BrainRoute
  FrontierRoute: typeof FrontierRoute
  GatesRoute: typeof GatesRoute
  HarborRoute: typeof HarborRoute
  IngestRoute: typeof IngestRoute
  IntelRoute: typeof IntelRoute
  MemoryRoute: typeof MemoryRoute
  MeshRoute: typeof MeshRoute
  ModelsRoute: typeof ModelsRoute
  ProofRoute: typeof ProofRoute
  ApiCycleRoute: typeof ApiCycleRoute
  ApiEstateRoute: typeof ApiEstateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiSourceRoute: typeof ApiSourceRoute
  ApiWorkstreamsRoute: typeof ApiWorkstreamsRoute
  ApiAgentStateRoute: typeof ApiAgentStateRoute
  ApiCodexRoute: typeof ApiCodexRoute
  ApiKernelsRoute: typeof ApiKernelsRoute
  ApiLeasesRoute: typeof ApiLeasesRoute
  ApiPinRoute: typeof ApiPinRoute
  ApiTriadRoute: typeof ApiTriadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adversary': {
      id: '/adversary'
      path: '/adversary'
      fullPath: '/adversary'
      preLoaderRoute: typeof AdversaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontier': {
      id: '/frontier'
      path: '/frontier'
      fullPath: '/frontier'
      preLoaderRoute: typeof FrontierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harbor': {
      id: '/harbor'
      path: '/harbor'
      fullPath: '/harbor'
      preLoaderRoute: typeof HarborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cycle': {
      id: '/api/cycle'
      path: '/api/cycle'
      fullPath: '/api/cycle'
      preLoaderRoute: typeof ApiCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estate': {
      id: '/api/estate'
      path: '/api/estate'
      fullPath: '/api/estate'
      preLoaderRoute: typeof ApiEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workstreams': {
      id: '/api/workstreams'
      path: '/api/workstreams'
      fullPath: '/api/workstreams'
      preLoaderRoute: typeof ApiWorkstreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-state': {
      id: '/api/agent-state'
      path: '/api/agent-state'
      fullPath: '/api/agent-state'
      preLoaderRoute: typeof ApiAgentStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex': {
      id: '/api/codex'
      path: '/api/codex'
      fullPath: '/api/codex'
      preLoaderRoute: typeof ApiCodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kernels': {
      id: '/api/kernels'
      path: '/api/kernels'
      fullPath: '/api/kernels'
      preLoaderRoute: typeof ApiKernelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leases': {
      id: '/api/leases'
      path: '/api/leases'
      fullPath: '/api/leases'
      preLoaderRoute: typeof ApiLeasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pin': {
      id: '/api/pin'
      path: '/api/pin'
      fullPath: '/api/pin'
      preLoaderRoute: typeof ApiPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/triad': {
      id: '/api/triad'
      path: '/api/triad'
      fullPath: '/api/triad'
      preLoaderRoute: typeof ApiTriadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AdversaryRoute: AdversaryRoute,
  BrainRoute: BrainRoute,
  FrontierRoute: FrontierRoute,
  GatesRoute: GatesRoute,
  HarborRoute: HarborRoute,
  IngestRoute: IngestRoute,
  IntelRoute: IntelRoute,
  MemoryRoute: MemoryRoute,
  MeshRoute: MeshRoute,
  ModelsRoute: ModelsRoute,
  ProofRoute: ProofRoute,
  ApiCycleRoute: ApiCycleRoute,
  ApiEstateRoute: ApiEstateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiSourceRoute: ApiSourceRoute,
  ApiWorkstreamsRoute: ApiWorkstreamsRoute,
  ApiAgentStateRoute: ApiAgentStateRoute,
  ApiCodexRoute: ApiCodexRoute,
  ApiKernelsRoute: ApiKernelsRoute,
  ApiLeasesRoute: ApiLeasesRoute,
  ApiPinRoute: ApiPinRoute,
  ApiTriadRoute: ApiTriadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
