/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AdversaryRouteImport } from './routes/adversary'
import { Route as FrontierRouteImport } from './routes/frontier'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ProofRouteImport } from './routes/proof'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdversaryRoute = AdversaryRouteImport.update({
  id: '/adversary',
  path: '/adversary',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontierRoute = FrontierRouteImport.update({
  id: '/frontier',
  path: '/frontier',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/adversary': typeof AdversaryRoute
  '/frontier': typeof FrontierRoute
  '/gates': typeof GatesRoute
  '/ingest': typeof IngestRoute
  '/intel': typeof IntelRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/models': typeof ModelsRoute
  '/proof': typeof ProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/adversary': typeof AdversaryRoute
  '/frontier': typeof FrontierRoute
  '/gates': typeof GatesRoute
  '/ingest': typeof IngestRoute
  '/intel': typeof IntelRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/models': typeof ModelsRoute
  '/proof': typeof ProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/adversary': typeof AdversaryRoute
  '/frontier': typeof FrontierRoute
  '/gates': typeof GatesRoute
  '/ingest': typeof IngestRoute
  '/intel': typeof IntelRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/models': typeof ModelsRoute
  '/proof': typeof ProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/adversary'
    | '/frontier'
    | '/gates'
    | '/ingest'
    | '/intel'
    | '/memory'
    | '/mesh'
    | '/models'
    | '/proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/adversary'
    | '/frontier'
    | '/gates'
    | '/ingest'
    | '/intel'
    | '/memory'
    | '/mesh'
    | '/models'
    | '/proof'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/adversary'
    | '/frontier'
    | '/gates'
    | '/ingest'
    | '/intel'
    | '/memory'
    | '/mesh'
    | '/models'
    | '/proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AdversaryRoute: typeof AdversaryRoute
  FrontierRoute: typeof FrontierRoute
  GatesRoute: typeof GatesRoute
  IngestRoute: typeof IngestRoute
  IntelRoute: typeof IntelRoute
  MemoryRoute: typeof MemoryRoute
  MeshRoute: typeof MeshRoute
  ModelsRoute: typeof ModelsRoute
  ProofRoute: typeof ProofRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adversary': {
      id: '/adversary'
      path: '/adversary'
      fullPath: '/adversary'
      preLoaderRoute: typeof AdversaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontier': {
      id: '/frontier'
      path: '/frontier'
      fullPath: '/frontier'
      preLoaderRoute: typeof FrontierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AdversaryRoute: AdversaryRoute,
  FrontierRoute: FrontierRoute,
  GatesRoute: GatesRoute,
  IngestRoute: IngestRoute,
  IntelRoute: IntelRoute,
  MemoryRoute: MemoryRoute,
  MeshRoute: MeshRoute,
  ModelsRoute: ModelsRoute,
  ProofRoute: ProofRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
